### PR TITLE
Bump release to 2.0.1

### PR DESCRIPTION
**Pull request by rmax**

### CODE REVIEW

**Comment by rmax** [comment]
Friendly nudge.

**Comment by parthea** [comment]
@MaartenBreddels, please could you take a look?

**Comment by parthea** [comment]
@jakirkham, please could you take a look?

**Comment by maartenbreddels** [comment]
Sorry, got lost between all the email, looks good.

**Comment by parthea** [comment]
Thanks @maartenbreddels !

**Pull request merged**
